name: bedtools_shift
description: Shifts features in a bedfile by a specified number of bases or proportion of the feature
keywords:
  - shift
  - bed
tools:
  - bedtools:
      description: |
        A set of tools for genomic analysis tasks, specifically enabling genome arithmetic (merge, count, complement) on various file types.
      documentation: https://bedtools.readthedocs.io/en/latest/content/tools/intersect.html

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bed:
      type: file
      description: BED feature file
      pattern: "*.{bed}"
  - fai:
      type: file
      description: Input fasta index file
      pattern: "*.{fai}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
  - bed:
      type: file
      description: Shifted BED feature file
      pattern: "*.{bed}"

authors:
  - "@marc-jones"
