name: test-modules

on:
  #push:
  #  branches: [ feat-chris ]
  pull_request:
    branches: [ master ]

jobs:
  test-modules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nxf_ver: ['20.07.1','']
        tag: ['base']
        docker-name: ['Dockerfile']
        module-name: []
        # include:
        #   - nxf_ver: '20.07.1'
        #     tag: 'cpu'
        #     docker-name: 'Dockerfile.cpu'
        #     module-name: 'guppy'
        #   - nxf_ver: ''
        #     tag: 'cpu'
        #     docker-name: 'Dockerfile.cpu'
        #     module-name: 'guppy'
    steps:
      - uses: actions/checkout@v2
      - name: Set version and tags
        id: ver
        run: |
          VERSION="0.0.0"
          test -f software/${{matrix.module-name}}/${{matrix.docker-name}} && export DOCKER_EXISTS=true || echo "Dockerfile does not exist, skipping step"
          if [ -v DOCKER_EXISTS ]; then VERSION=`cat software/${{matrix.module-name}}/VERSION` && echo "::set-output name=version::$(echo $VERSION)"; fi
          if [ $? -ne 0 ]; then exit 1; fi
          echo "version: $VERSION"
        shell: bash
      - name: Install Nextflow
        run: |
          export NXF_VER=${{matrix.nxf_ver}}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Docker build
        run: |
           test -f software/${{matrix.module-name}}/${{matrix.docker-name}} && export DOCKER_EXISTS=true || echo "Dockerfile does not exist, skipping step"
           if [ -v DOCKER_EXISTS ]; then docker build -f software/${{matrix.module-name}}/${{matrix.docker-name}} -t luslab/nf-modules-${{matrix.module-name}}:latest -t luslab/nf-modules-${{matrix.module-name}}:${{matrix.tag}}-${{steps.ver.outputs.version}} software/${{matrix.module-name}}; fi
      - name: Module testing
        run: |
          nextflow -C ${GITHUB_WORKSPACE}/software/${{matrix.module-name}}/test/nextflow.config run ${GITHUB_WORKSPACE}/software/${{matrix.module-name}}/test/main.nf
