name: peka
description: Runs PEKA CLIP peak k-mer analysis
keywords:
  - PEKA
  - k-mer
  - CLIP
tools:
  - peka:
      description: Positionally-enriched k-mer analysis (PEKA) is a software package for identifying enriched protein-RNA binding motifs from CLIP datasets
      homepage: https://github.com/ulelab/peka
      documentation: None
      tool_dev_url: None
      doi: ""
      licence: ['GPL-3.0']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - peaks:
      type: file
      description: BED file of peak regions
      pattern: "*.{bed,bed.gz}"
  - crosslinks:
      type: file
      description: BED file of crosslinks
      pattern: "*.{bed,bed.gz}"
  - genome:
      type: file
      description: Genome reference sequence used
      pattern: "*.{fa}"
  - fai:
      type: file
      description: FAI file corresponding to the reference sequence
      pattern: "*.{fai}"
  - gtf:
      type: file
      description: A segmented GTF used to annotate peaks
      pattern: "*.{gtf}"

output:
  - cluster:
      type: file
      description: TSV file of summed occurrence distributions of k-mers within defined clusters
      pattern: "*.tsv"
  - distribution:
      type: file
      description: TSV file with calculated PEKA score and occurrence distribution for all possible k-mers
      pattern: "*.tsv"
  - pdf:
      type: file
      description: PDF file with graphs showing k-mer occurrence distributions around thresholded crosslink sites
      pattern: "*.pdf"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"

authors:
  - "@codeprimate123"
  - "@kkuret"
