name: ultraplex

description: Ultraplex is an all-in-one software package for processing and demultiplexing fastq files.
keywords:
  - demultiplexer
  - fastq
  - umi
tools:
  - ultraplex:
      description: fastq demultiplexer
      homepage: https://github.com/ulelab/ultraplex
      documentation: https://github.com/ulelab/ultraplex
      tool_dev_url: https://github.com/ulelab/ultraplex
      doi: "10.5281/zenodo.465128"
      licence: ['MIT']


input:
  - fastq:
      type: file
      description: Zipped FASTQ file
      pattern: "*.{fastq.gz}"

output:
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
  - fastq:
      type: file
      description: Demultiplexed sample FASTQ files
      pattern: "*[!no_match].fastq.gz"
  - no_match_fastq:
      type: file
      description: FASTQ file containing reads that could not be demultiplexed
      pattern: "*no_match.fastq.gz"
  - report:
      type: file
      description: File containing demultiplexing log
      pattern: "*.log"

authors:
  - "@charlotteanne"
  - "@oscarwilkins"
