name: lint-dockerfiles
#https://github.com/hadolint/hadolint

on:
  pull_request:
    branches: [ dev, main ]
  # push:
  #   branches: [ feat-testing ]

jobs:
  lint-docker:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          docker-name: ['Dockerfile']
          module-name: ['r']
    steps:
      - uses: actions/checkout@v2
      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: modules/${{matrix.module-name}}/${{matrix.docker-name}}
